
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot_cache?serverTimezone=Asia/Shanghai
    username: yzy
    password: 19970806
  redis:
    host: 192.168.116.151
mybatis:
  configuration:
    map-underscore-to-camel-case: true

debug: true
logging:
  level:
    com.clownfish7.springbootcache.mapper: debug
