
management:
    endpoints:
        web:
          exposure:
            include: "*"
    endpoint:
      shutdown:
        enabled: true
      health:
        show-details: always
spring:
  redis:
    host: localhost
info:
  author: clownfish7
  version: v1.0

# 主要的端点:
# HTTP方法   路径                 描述
# GET       /autoconfig         查看自动配置的使用情况
# GET       /configprops        查看配置属性，包括默认配置
# GET       /beans              查看bean及其关系列表
# GET       /dump               打印线程栈
# GET       /env                查看所有环境变量
# GET       /env/{name}         查看具体变量值
# GET       /health             查看应用健康指标
# GET       /info               查看应用信息
# GET       /mappings           查看所有url映射
# GET       /metrics            查看应用基本指标
# GET       /metrics/{name}     查看具体指标
# POST      /shutdown           关闭应用
# GET       /trace              查看基本追踪信息

#id               desc                                                    Sensitive
#auditevents      显示当前应用程序的审计事件信息                               Yes
#beans            显示应用Spring Beans的完整列表                             Yes
#caches           显示可用缓存信息                                           Yes
#conditions       显示自动装配类的状态及及应用信息                              Yes
#configprops      显示所有 @ConfigurationProperties 列表                     Yes
#env              显示 ConfigurableEnvironment 中的属性                      Yes
#??#flyway        显示 Flyway 数据库迁移信息                                    Yes
#health           显示应用的健康信息(未认证只显示status，认证显示全部信息详情)      No
#info             显示任意的应用信息(在资源文件写info.xxx即可)                   No
#??#liquibase     展示Liquibase 数据库迁移                                     Yes
#metrics          展示当前应用的 metrics 信息                                  Yes
#mappings         显示所有 @RequestMapping 路径集列表                          Yes
#scheduledtasks   显示应用程序中的计划任务                                      Yes
#??#sessions      允许从Spring会话支持的会话存储中检索和删除用户会话。             Yes
#shutdown         允许应用以优雅的方式关闭(默认情况下不启用)                      Yes
#threaddump       执行一个线程dump                                            Yes
#httptrace        显示HTTP跟踪信息(默认显示最后100个HTTP请求 - 响应交换)          Yes

#配置文件中文git上传变ASCII测试