
spring:
  elasticsearch:
    jest:
      uris: http://192.168.116.151:9200
      username:
      password:
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.116.151:9300