spring:
  activiti:
    database-schema-update: true
    db-history-used: true
    history-level: activity
    check-process-definitions: true
#    process-definition-location-prefix: classpath:/processes
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.97.8.7:3306/activity7_y2y_another?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: dev
    password: pass
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      connection-test-query: select 1
#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  #  typeAliasesPackage: io.renren.modules.*.entity
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      #field-strategy: NOT_NULL
      #驼峰下划线转换
      table-underline: true
      #logic-delete-value: -1
      #logic-not-delete-value: 0
    banner: false
  #原生配置
  configuration:
    # 配置slq打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启驼峰命名
    map-underscore-to-camel-case: true
    # 关闭缓存
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
debug: false


# 参数说明：
#
# databaseSchemaUpdate配置项可以设置流程引擎启动和关闭时数据库执行的策略。 databaseSchemaUpdate有以下四个值：
#   false：false为默认值，设置为该值后，Activiti在启动时，会对比数据库表中保存的版本，如果没有表或者版本不匹配时，将在启动时抛出异常。
#   true：设置为该值后，Activiti会对数据库中所有的表进行更新，如果表不存在，则Activiti会自动创建。
#   create-drop：Activiti启动时，会执行数据库表的创建操作，在Activiti关闭时，会执行数据库表的删除操作。
#   drop-create：Activiti启动时，会执行数据库表的删除操作，在Activiti关闭时，会执行数据库表的创建操作。
#
# history-level对于历史数据，保存到何种粒度，Activiti提供了history-level属性对其进行配置。history-level属性有点像log4j的日志输出级别，该属性有以下四个值：
#   none：不保存任何的历史数据，因此，在流程执行过程中，这是最高效的。
#   activity：级别高于none，保存流程实例与流程行为，其他数据不保存。
#   audit：除activity级别会保存的数据外，还会保存全部的流程任务及其属性。audit为history的默认值。
#   full：保存历史数据的最高级别，除了会保存audit级别的数据外，还会保存其他全部流程相关的细节数据，包括一些流程参数等。
#   db-history-used为true表示使用历史表，如果不配置，则工程启动后可以检查数据库，只建立了17张表，历史表没有建立，则流程图及运行节点无法展示

