server:
  port: 8082

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.116.170:3306/try?useSSL=false
    username: root
    password: 123456
  rabbitmq:
    host: 192.168.116.170
    username: root
    password: root
    virtual-host: /
    port: 5672
  redis:
    host: 192.168.116.170
    port: 6379
    password: ps@123

#mybatis
mybatis-plus:
  #  mapper-locations: classpath*:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  #  typeAliasesPackage: io.renren.modules.*.entity
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: none
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      insert-strategy: not_null
      #驼峰下划线转换
      table-underline: true
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false
  #原生配置
  configuration:
    # 配置slq打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启驼峰命名
    map-underscore-to-camel-case: true
    # 关闭缓存
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
debug: true
